name: Overlord
version: '1.1'
main: org.skz.overlord.Overlord
api-version: '1.21'
authors:
  - SKZ_azerty
  - Alpha
permissions:
  permission.op:
    default: op
commands:
  resetdeaths:
    permission: permission.op
  createnewworld:
    permission: permission.op
  wando:
    permission: permission.op
  protect:
    permission: permission.op
  region:
    permission: permission.op
  bsave:
    permission: permission.op
  bload:
    permission: permission.op
  bundo:
    permission: permission.op
